2016-03-23 15:13:57,184 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-23 15:13:57,743 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-23 15:16:19,143 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-23 15:16:53,005 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-23 16:48:15,650 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-23 16:48:33,226 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:41:25,815 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:42:39,788 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:50:13,351 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:50:13,954 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:50:20,816 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:53:21,310 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:55:14,294 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:56:06,233 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 09:56:50,274 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:02:53,535 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:05:39,951 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:27:54,747 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:31:04,207 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:31:25,090 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:32:14,918 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:32:27,939 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:32:39,718 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:32:41,179 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:33:05,006 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:37:46,260 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:39:17,968 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:39:41,804 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:40:27,881 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:48:02,867 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:49:07,274 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:54:23,076 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:59:00,211 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:59:04,997 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:59:28,468 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 10:59:59,255 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:00:31,066 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:00:48,921 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:00:53,734 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:01:43,827 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:02:04,307 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:02:26,027 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:02:55,518 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:02:58,207 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:02:59,727 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:06:48,276 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:36:26,829 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:36:27,438 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:37:51,958 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:39:16,958 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:40:49,497 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:43:40,853 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:43:41,323 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:43:54,273 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:47:06,658 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:51:51,391 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:55:30,320 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:56:11,201 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-24 11:58:12,201 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-30 23:47:02,223 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:55]
2016-03-31 01:56:00,634 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:65]
2016-03-31 02:16:35,347 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:65]
2016-03-31 02:16:49,359 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:65]
2016-03-31 02:16:56,392 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:17:47,683 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:17:57,169 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:18:06,224 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:18:37,102 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:18:38,165 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:18:39,061 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:22:17,036 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:22:17,863 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:22:32,690 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:65]
2016-03-31 02:22:39,992 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:22:42,774 ERROR: Exception on /inmates/penalrecords [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 138, in penal_record
    form = PenalRecordForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:23:21,841 ERROR: Exception on /admin/inmate/ [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 981, in get_list
    count = count_query.scalar() if count_query else None
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2504, in scalar
    ret = self.one()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: inmate [SQL: u'SELECT count(?) AS count_1 \nFROM inmate'] [parameters: ('*',)]
2016-03-31 02:23:26,934 ERROR: Exception on /admin/penalrecord/ [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 981, in get_list
    count = count_query.scalar() if count_query else None
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2504, in scalar
    ret = self.one()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: penal_record [SQL: u'SELECT count(?) AS count_1 \nFROM penal_record'] [parameters: ('*',)]
2016-03-31 02:23:31,851 ERROR: Exception on /admin/inmate/ [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 981, in get_list
    count = count_query.scalar() if count_query else None
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2504, in scalar
    ret = self.one()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: inmate [SQL: u'SELECT count(?) AS count_1 \nFROM inmate'] [parameters: ('*',)]
2016-03-31 02:24:30,157 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:25:44,055 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:65]
2016-03-31 02:25:47,840 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:25:57,348 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:26:05,352 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:29:57,648 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:33:35,264 ERROR: Exception on /inmates/transfers [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 148, in transfer
    form = TransferForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:34:29,594 ERROR: Exception on /inmates/add [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 48, in add_inmate
    form = InmateForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:41:42,239 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 02:41:49,351 ERROR: Exception on /inmates/transfers [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 148, in transfer
    form = TransferForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:42:03,244 ERROR: Exception on /inmates/nextofkin [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/current/jmremote/jail-manager/app/inmates/views.py", line 128, in add_next_of_kin
    form = NextOfKinForm()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 96, in __init__
    *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/wtforms/ext/csrf/form.py", line 22, in __init__
    self.csrf_token.current_token = self.generate_csrf_token(csrf_context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in generate_csrf_token
    return generate_csrf(self.SECRET_KEY, self.TIME_LIMIT)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_wtf/csrf.py", line 43, in generate_csrf
    raise Exception('Must provide secret_key to use csrf.')
Exception: Must provide secret_key to use csrf.
2016-03-31 02:56:15,700 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 02:56:25,791 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 02:56:26,272 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 02:57:44,839 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 02:57:53,393 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:00:17,374 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:00:27,932 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:00:33,262 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:00:33,673 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:01:39,811 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:06:40,720 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:06:47,309 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:06:47,714 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:08:58,344 INFO: jailermanager startup [in app/__init__.py:63]
2016-03-31 03:12:26,261 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:15:07,315 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:15:16,337 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:15:39,758 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:15:57,606 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:16:02,494 ERROR: Exception on /admin/penalrecord/ [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 981, in get_list
    count = count_query.scalar() if count_query else None
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2504, in scalar
    ret = self.one()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: penal_record [SQL: u'SELECT count(?) AS count_1 \nFROM penal_record'] [parameters: ('*',)]
2016-03-31 03:16:06,502 ERROR: Exception on /admin/penalrecord/ [GET] [in /Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 68, in inner
    return self._run_view(f, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/base.py", line 367, in _run_view
    return fn(self, *args, **kwargs)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/model/base.py", line 1738, in index_view
    view_args.search, view_args.filters)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/flask_admin/contrib/sqla/view.py", line 981, in get_list
    count = count_query.scalar() if count_query else None
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2504, in scalar
    ret = self.one()
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2473, in one
    ret = list(self)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2516, in __iter__
    return self._execute_and_instances(context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2531, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/Users/anyemi/devhud/python/venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: penal_record [SQL: u'SELECT count(?) AS count_1 \nFROM penal_record'] [parameters: ('*',)]
2016-03-31 03:16:19,612 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:16:20,014 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:16:45,875 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:16:56,722 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:17:22,077 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:17:41,285 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:17:51,835 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:18:05,341 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:18:05,739 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 03:18:48,654 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
2016-03-31 09:22:27,489 INFO: jailermanager startup [in /Users/anyemi/devhud/current/jmremote/jail-manager/app/__init__.py:63]
